function burstdet_optgui(mainWinH)
% gui for setting analysis & general options within threshdetgui

% ***************** WATCH OUT *********************************************
% whenever you (as the programmer) make any change to this gui, including 
% and notably the callbacks of the buttons, saved parameter files must be 
% recreated by the user because these parameter files are matlab
% 'fig'-files which store everything, including the callbacks. 'Recreating'
% does not necessarily mean retyping all values from scratch. In case only
% the callbacks changed, do the following:
% open options dialogue
% - load old parameter file
% - hit 'apply' button
% - close window manually if it does not close automatically
% - reopen options dialogue
% - save (same or other name), done!
% *************************************************************************

% standard dimension of edit fields
editw=.15;
edith=.038*2;

% standard dimensions of buttons
butt1x=.1;
butt1y=.035*2;
butt2x=.2;
butt2y=.07*2;

% elementary delta y given height of text fields and smaller buttons
dy=.04*2;
% standard text field width 
textw=.25;
% left & right alignment lines in ascending order
la0=.005;
la1=butt1x*1.15;
la2=la1+textw*1.05;
la3=la2+editw+.01;
la4=la3+textw*1.05;
la5=la4+editw+.01;
% vertical separators from top to bottom
ba1=.87;
ba2=.55;
ba11=.33;

% font sizes
fsz=9;
fsz_big=13;

% callback for buttons
funcH=@burstdetguifunc;

% if gui exists from previous session, delete it
tmph=findobj('name', 'options', 'type', 'figure');
if ~isempty(tmph)
  delete(tmph);
end


% create (new) GUI window, filling space below main window

H0 = figure('Units','normalized', ...
   'Color',[0.8 0.8 0.8], ...
   'Name','options', ...
   'NumberTitle','off', ...
   'Position',[0.005 0.05 0.99 0.27], ...
   'Tag','options',...
   'MenuBar','none',...
   'Toolbar','none'...
);

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% ~~~ buttons must come first because of callbacks of edit fields)
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la0 ba1-1*butt2y butt1x butt2y], ...
  'FontSize',fsz, ...
  'Fontweight','bold',...
  'style','pushbutton',...  
  'String','load from file', ...
  'TooltipString','',...
  'Tag','loadParBttn', ...
  'callback', {funcH,{'readOptionsFromFile'}});  

uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la0 ba1-2*butt2y butt1x butt2y], ...
  'FontSize',fsz, ...
  'Fontweight','bold',...
  'style','pushbutton',...  
  'String','save to file', ...
  'TooltipString','',...
  'Tag','saveParBttn', ...
  'callback', {funcH,{'writeOptions2File'}});  

uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la0 ba1-3*butt2y butt1x butt2y], ...
  'FontSize',fsz, ...
  'Fontweight','bold',...
  'style','pushbutton',...  
  'String','apply', ...
  'TooltipString','',...
  'Tag','OKParBttn', ...
  'callback', {funcH,{'readOptionsFromGui'}});  

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% ~~~ burst detection section
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-0*dy la2-la1+editw edith], ...
  'FontSize',fsz, ...
  'FontWeight','bold', ...
  'BackgroundColor',[0.6 0.6 0.6], ...
  'Style','text', ...
  'String','~~~~~ burst detection', ...
  'Tag','headline2');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-1*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','INITIAL inter-event interval (ms)', ...
  'Tag','text_maxIEI_init');
hh=uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-1*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','maxIEI_init');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-2*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','LATE inter-event interval (ms)', ...
  'Tag','text_maxIEI_tail');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-2*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','maxIEI_tail');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-3*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','minimal # events per burst', ...
  'Tag','text_minNEvPerBurst');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-3*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','minNEvPerBurst');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-4*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','min. dur. pre-burst silent period (ms)', ...
  'Tag','text_minPreBurstSilentPerLen');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-4*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','minPreBurstSilentPerLen');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-5*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','max. # events in pre-burst silent period', ...
  'Tag','text_maxPreBurstSilentPerNEv');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-5*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','maxPreBurstSilentPerNEv');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-6*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','max. length of ''normal'' burst (ms)', ...
  'TooltipString','any burst longer than this will be tagged a ''freak event'' (but will still enter all statistics)',...  
  'Tag','text_maxNormalBurstLength');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-6*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','maxNormalBurstLength');

% *** currently inactive UIs (see property 'visible'***
% uicontrol('Parent',H0, ...
%   'Units','normalized', ...   
%   'HorizontalAlignment','left', ...
%   'Position',[la1 ba1-3*dy textw edith], ...  
%   'FontSize',fsz, ...
%   'BackgroundColor',[0.8 0.8 0.8], ...
%   'Style','text', ...  
%   'visible', 'off', ...
%   'String','accept single event as burst', ...
%   'callback', {funcH,{'optionsDialogAlert'}},...
%   'Tag','text_isBurstSingleEv');
% uicontrol('Parent',H0, ...
%   'Units','normalized', ...
%   'HorizontalAlignment','left', ...
%   'Position', [la2 ba1-3*dy editw edith], ... 
%   'FontSize',fsz, ...   
%   'BackgroundColor',[0.8 0.8 0.8], ...
%   'Style','checkbox', ...
%   'visible', 'off', ...
%   'callback', {funcH,{'optionsDialogAlert'}},...
%   'Tag','isBurstSingleEv');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la1 ba1-4*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'visible', 'off', ...
  'String','minimal burst length (ms)', ...
  'Tag','text_minBurstLen');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la2 ba1-4*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'visible', 'off', ...
  'Tag','minBurstLen');


% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% ~~~ display options
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-0*dy la4-la3+editw edith], ...
  'FontSize',fsz, ...
  'FontWeight','bold', ...
  'BackgroundColor',[0.6 0.6 0.6], ...
  'Style','text', ...
  'String','~~~~~ display options', ...
  'Tag','headline3');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-1*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','raster: time per line (s)', ...
  'Tag','text_OvPlotTAx');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4 ba1-1*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','OvPlotTAx');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-2*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','peri-burst time interval (ms)', ...
  'Tag','text_pethInterval');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4 ba1-2*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','pethInterval');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-3*dy textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','pbth: bin width (ms)', ...
  'Tag','text_pethBinWid');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4 ba1-3*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','pethBinWid');


% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% ~~~ saving options
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-6*dy la4-la3+editw edith], ...
  'FontSize',fsz, ...
  'FontWeight','bold', ...
  'BackgroundColor',[0.6 0.6 0.6], ...
  'Style','text', ...
  'String','~~~~~ saving options', ...
  'Tag','headline4');

uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[la3 ba1-7*dy textw edith], ...
  'FontSize',fsz, ...
  'BackgroundColor',[0.8 0.8 0.8], ...
  'Style','text', ...  
  'String','string in result file name (ASCII only)', ...
  'Tag','text_resFnString');
uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4 ba1-7*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH,{'optionsDialogAlert'}},...
  'Tag','resFnString');

