function burstdetgui
% ** function burstdetgui
% Graphical user interface for defining bursts from events (action
% potentials, field potentials) listed in time stamp list

% Here, layout of all gui elements (knobs, buttons, etc.) should be done

labelscale('fontSz',8,'scaleFac',1.0,'lineW',.25,'markSz',6); 
% standard dimension of edit fields
editw=.08;
edith=.032;
% standard dimensions of buttons
butt1x=.16;
butt1y=.05;
butt2x=.16;
butt2y=.10;

% elementary delta y given height of text fields and smaller buttons
dy=.036;
% standard text field width (at least as wide as big buttons)
textw=.16;
% standard margin for major divisions of figure (like plots and groups of buttons)
smarg=.025;

% left alignment lines in ascending order
la1=smarg;
% left border of left-aligned subplots
la2=la1+textw+1.5*smarg;
la3=la2+.2+smarg;
la4=.75+smarg;

% vertical separators from top to bottom
ba1=.96;
ba2=.55;
ba11=.33;

% font sizes
fsz=9;
fsz_big=12;

% if gui exists from previous session, delete it
tmph=findobj('name', 'Burst Determination', 'type', 'figure');
if ~isempty(tmph)
  delete(tmph);
end

% the collection of routines associated with most button callbacks
funcH1=@burstdetguifunc;

% create GUI window
H0 = figure('Units','normalized', ...
   'Color',[0.8 0.8 0.8], ...
   'Name','Burst Determination', ...
   'NumberTitle','off', ...
   'Position',[0.005 0.35 0.99 0.6], ...
   'Tag','SpikeDet',...
   'MenuBar','none',...
   'Toolbar','figure'...
);

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la1 ba1-1*butt2y butt2x butt2y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','read data', ...
  'TooltipString','',...
  'Tag','readDataBttn', ...
  'callback', {funcH1,{'readData'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la1 ba1-2*butt2y butt2x butt2y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','options..', ...
  'TooltipString','',...
  'Tag','optionsBttn', ...
  'callback', {funcH1,{'openOptionsDialog'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la1 ba1-3*butt2y butt2x butt2y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','detect bursts', ...
  'TooltipString','',...
  'Tag','detBurstBttn', ...
  'callback', {funcH1,{'detBurst'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la1 ba1-4*butt2y butt2x butt2y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','save results', ...
  'TooltipString','',...
  'Tag','saveResBttn', ...
  'callback', {funcH1,{'saveResults'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la1 ba1-6*butt2y butt2x butt2y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','EXIT', ...
  'TooltipString','And now for something completely different...',...
  'ListboxTop',0, ...
  'Tag','doneBttn', ...
  'callback', {funcH1,{'done'}});  

% Set up the subplots and don't forget to tag them so they can be
% identified (plots need larger margins because of axes labels).
% From top to bottom, left to right:
% - overview tsl
sp.tslOv.axH=subplot('position',[la2  0.32+1.5*smarg  la4-la2-smarg  0.68-3*smarg]);
set(sp.tslOv.axH,'tag','tslOverview','NextPlot','add');
% - aligned bursts
sp.tslExc.axH=subplot('position',[la4  0.25+1.5*smarg  1-la4-smarg  0.75-3*smarg]);
set(sp.tslExc.axH,'tag','tslExcerpt');
% - info window
sp.info.axH=subplot('position',[la1  2.0*smarg  butt2x  0.3-2.0*smarg]);
set(sp.info.axH,'tag','info');
% - iei
sp.iei.axH=subplot('position',[la2  0.16+1.5*smarg  la4-la2-smarg  0.16-1.5*smarg]);
set(sp.iei.axH,'tag','iei');
% - raw excerpts
sp.rawExc.axH=subplot('position',[la2  2.0*smarg  la4-la2-smarg  0.14-2.0*smarg]);
set(sp.rawExc.axH,'tag','rawExc');
% - peth
sp.peth.axH=subplot('position',[la4  2.0*smarg  1-la4-smarg  0.25-2.0*smarg]);
set(sp.peth.axH,'tag','peth');

burstdetguifunc(H0,[],{'init','openOptionsDialog'},'sp',sp);
